# SMS Server - App

version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_ENV: "${DOCKER_ENV:-development}"
    ports:
      - "${DOCKER_APP_PORT:-8080}:8080"
    env_file:
      - .env
    restart: always
