# SMS App

version: "3.8"
services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms-app-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:?err}:8080"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
volumes:
  pgdata:
