# SMS App - Production

version: "3.8"
services:
  db:
    restart: unless-stopped
  server:
    restart: unless-stopped
    build:
      args:
        dockerenv: production
    environment:
      NODE_ENV: production
