name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Set up .env file
      env:
        PRODUCTION_ENV_FILE: ${{ secrets.PRODUCTION_ENV_FILE }}
      run: echo "$PRODUCTION_ENV_FILE" | base64 --decode > .env

    - name: Set Docker project name
      run: export COMPOSE_PROJECT_NAME=sms_server

    - name: Set Docker build arg
      run: export DOCKER_ENV=production
      
    - name: Rebuild & restart container
      run: sudo docker-compose up --build --detach app

    - name: Run migrations
      run: sudo docker exec sms_server_app_1 npx sequelize-cli db:migrate