name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: self-hosted

    env:
      PORT: ${{ secrets.PORT }}
      DOMAIN: ${{ secrets.DOMAIN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Rebuild and restart docker container
      run: |
        sudo \
        PORT="$PORT" \
        DOMAIN="$DOMAIN" \
        JWT_SECRET="$JWT_SECRET" \
        SESSION_SECRET="$SESSION_SECRET" \
        TWILIO_ACCOUNT_SID="$TWILIO_ACCOUNT_SID" \
        TWILIO_AUTH_TOKEN="$TWILIO_AUTH_TOKEN" \
        MAILGUN_API_KEY="$MAILGUN_API_KEY" \
        MAILGUN_DOMAIN="$MAILGUN_DOMAIN" \
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
